---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  namespace: frontend
  labels:
    app: landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
        - name: landing
          image: ghcr.io/robosell-organization/rb-landing:main
          ports:
            - containerPort: 3000
          
          imagePullPolicy: Always

      imagePullSecrets:
        - name: ghcr-login-secret
      
  revisionHistoryLimit: 1



---
apiVersion: v1
kind: Service
metadata:
  name: landing
  namespace: frontend
spec:
  selector:
    app: landing
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
