import type { TabPlanProps, PricingPlanProps } from '@/types/plan'

export const TAB_PLANS: TabPlanProps = {
	monthly: {
		label: '1 Oylik',
		months: 1,
		discount: 0,
		value: 'monthly',
	},
	halfYearly: {
		label: '6 oylik',
		discount: 15,
		value: 'halfYearly',
		months: 6,
	},
	yearly: {
		label: '1 yillik',
		discount: 20,
		value: 'yearly',
		months: 12,
	},
}

export const PRICING_PLANS: PricingPlanProps = {
	BASIC: {
		title: 'Basic Plan',
		isPopular: false,
		desc: 'Perfect plan for starters',
		banner: 1,
		promocode: false,
		source: true,
		product: 250,
		discount: true,
		branch: 2,
		mailing: 3,
		chat: true,
		stock: false,
		analytics: false,
		export: false,
		price: 200000,
		type: 'BASIC',
		color: 'PURPLE',
	},
	PROFESSIONAL: {
		title: 'Professional Plan',
		isPopular: true,
		desc: 'For companies want to do more',
		banner: 5,
		promocode: true,
		source: true,
		product: 5000,
		discount: true,
		branch: 10,
		mailing: 20,
		chat: true,
		stock: true,
		analytics: true,
		export: false,
		price: 400000,
		type: 'PROFESSIONAL',
		color: 'GREEN',
	},
	ENTERPRISE: {
		title: 'Enterprise Plan',
		isPopular: false,
		desc: 'Run your company on your termns',
		banner: 10,
		promocode: true,
		source: true,
		product: -1,
		discount: true,
		branch: -1,
		mailing: -1,
		chat: true,
		stock: true,
		analytics: true,
		export: true,
		price: 700000,
		type: 'ENTERPRISE',
		color: 'ORANGE',
	},
}
